title: Maxime Poli
email: maxime.poli@eleves.enpc.fr
description: >- # this means to ignore newlines until "baseurl:"
    Master's degree student at École des Ponts ParisTech
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin: ""
github: ""

sections: Computer Vision, Speech Processing
# Build settings
markdown: redcarpet
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
